### ISSUE TITLE
`/about`に飛んだ際にpre-festivalが表示されない

### ISSUE THREAD

**Issue by senntou** [Nitech-Festival-Executive-Committee/koudaisai#30]
# 概要

`/about`ページに飛んだ際にpre-festivalが表示されない

# 説明
画像のパスが間違ってるっぽい？

# 目的

## やること
- [ ] 画像のパス見直し

**Comment by MurakawaTakuya** [comment]
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/blob/bd5713b236ce6655c895162f48e07e37d4378ce1/src/components/PreviousFestival/PreviousFestival.tsx#L18
相対パスになってるからだね
aboutのページでは`public/about/image`から画像を貰いに行ってる
