### ISSUE TITLE
CSSのメディアクエリを変数化する

### ISSUE THREAD

**Issue by senntou** [Nitech-Festival-Executive-Committee/koudaisai#31]
# 概要

CSSのメディアクエリを変数化する

# 説明
sassの機能を使うことで、メディアクエリの記述を変数化し統一したい

# 目的

```
@media screen and (max-width : 767px) {
}
```
を毎回書くのはやめたい

## やること
- [ ] メディアクエリの変数化
- [ ] 既存のメディアクエリの変更

**Comment by MurakawaTakuya** [comment]
informationが終わるまで待機
